# Sklearn

## sklearn.cross_validation

документация: http://scikit-learn.org/stable/modules/cross_validation.html

In [15]:
from sklearn import cross_validation, datasets

import numpy as np

### Разовое разбиение данных на обучение и тест с помощью train_test_split

In [2]:
iris = datasets.load_iris()

In [3]:
train_data, test_data, train_labels, test_labels = cross_validation.train_test_split(iris.data, iris.target, 
                                                                                     test_size = 0.3)

In [4]:
#убедимся, что тестовая выборка действительно составляет 0.3 от всех данных
float(len(test_labels))/len(iris.data)

0.3

In [6]:
print('Размер обучающей выборки: {} объектов \nРазмер тестовой выборки: {} объектов'.format(len(train_data),
                                                                                            len(test_data)))

Размер обучающей выборки: 105 объектов 
Размер тестовой выборки: 45 объектов


In [7]:
print('Обучающая выборка:\n', train_data[:5])
print('\n')
print('Тестовая выборка:\n', test_data[:5])

Обучающая выборка:
 [[ 4.8  3.4  1.9  0.2]
 [ 5.8  2.7  5.1  1.9]
 [ 4.8  3.   1.4  0.3]
 [ 6.7  3.   5.   1.7]
 [ 6.7  3.1  5.6  2.4]]


Тестовая выборка:
 [[ 5.8  2.6  4.   1.2]
 [ 6.4  2.7  5.3  1.9]
 [ 6.3  2.5  5.   1.9]
 [ 5.4  3.   4.5  1.5]
 [ 5.5  3.5  1.3  0.2]]


In [ ]:
print 'Метки классов на обучающей выборке:\n', train_labels
print '\n'
print 'Метки классов на тестовой выборке:\n', test_labels

### Стратегии проведения кросс-валидации

#### KFold

In [8]:
for train_indices, test_indices in cross_validation.KFold(10, n_folds = 5):
    print(train_indices, test_indices)

[2 3 4 5 6 7 8 9] [0 1]
[0 1 4 5 6 7 8 9] [2 3]
[0 1 2 3 6 7 8 9] [4 5]
[0 1 2 3 4 5 8 9] [6 7]
[0 1 2 3 4 5 6 7] [8 9]


In [14]:
cv = cross_validation.KFold(10, n_folds = 5)
for i,j in cv:
    print(i,' < - >',j)

[2 3 4 5 6 7 8 9]  < - > [0 1]
[0 1 4 5 6 7 8 9]  < - > [2 3]
[0 1 2 3 6 7 8 9]  < - > [4 5]
[0 1 2 3 4 5 8 9]  < - > [6 7]
[0 1 2 3 4 5 6 7]  < - > [8 9]


In [ ]:
for train_indices, test_indices in cross_validation.KFold(10, n_folds = 2, shuffle = True):
    print train_indices, test_indices

In [ ]:
for train_indices, test_indices in cross_validation.KFold(10, n_folds = 2, shuffle = True, random_state = 1):
    print train_indices, test_indices

#### StratifiedKFold

In [ ]:
target = np.array([0] * 5 + [1] * 5)
print target
for train_indices, test_indices in cross_validation.StratifiedKFold(target, n_folds = 2, shuffle = True, random_state = 0):
    print train_indices, test_indices

In [ ]:
target = np.array([0, 1] * 5)
print target
for train_indices, test_indices in cross_validation.StratifiedKFold(target, n_folds = 2,shuffle = True):
    print train_indices, test_indices

#### ShuffleSplit

In [ ]:
for train_indices, test_indices in cross_validation.ShuffleSplit(10, n_iter = 10, test_size = 0.2):
    print train_indices, test_indices

#### StratifiedShuffleSplit

In [18]:
target = np.array([0] * 5 + [1] * 5)
print(target)
for train_indices, test_indices in cross_validation.StratifiedShuffleSplit(target, n_iter = 4, test_size = 0.2):
    print(train_indices, test_indices)

[0 0 0 0 0 1 1 1 1 1]
[3 6 5 2 8 7 0 4] [9 1]
[6 3 1 0 7 9 2 5] [4 8]
[7 3 1 9 0 8 4 5] [2 6]
[6 1 8 5 4 0 9 3] [7 2]


In [22]:
a = cross_validation.StratifiedShuffleSplit(target, n_iter = 4, test_size = 0.2)
print(a)

StratifiedShuffleSplit(labels=[0 0 0 0 0 1 1 1 1 1], n_iter=4, test_size=0.2, random_state=None)


#### Leave-One-Out

In [ ]:
for train_indices, test_index in cross_validation.LeaveOneOut(10):
    print train_indices, test_index

Больше стратегий проведения кросс-валидации доступно здесь: http://scikit-learn.org/stable/modules/cross_validation.html#cross-validation-iterators